openapi: 3.0.3
info:
  title: TD OAS - Exo 1 - Ping
  version: 1.0.0
servers:
  - url: https://api.example.com
paths:
  /ping:
    get:
      summary: Simple ping endpoint
      responses:
        '200':
          description: Pong response
          content:
            text/plain:
              schema:
                type: string
              example: pong
