openapi: 3.0.3
info:
  title: TD OAS - Exo 2 - Users
  version: 1.0.0
servers:
  - url: https://api.example.com
components:
  parameters:
    PageParam:
      name: page
      in: query
      required: true
      schema: { type: integer, minimum: 1 }
      description: Numéro de page (>=1).
    SizeParam:
      name: size
      in: query
      required: true
      schema: { type: integer, minimum: 1, maximum: 200 }
      description: Nombre d'éléments par page.
  schemas:
    User:
      type: object
      required: [id, name, email]
      properties:
        id: { type: integer, example: 1 }
        name: { type: string, example: Alice }
        email: { type: string, format: email, example: alice@example.com }
    Error:
      type: object
      required: [error]
      properties:
        error: { type: string, example: Bad types for provided query parameters }
paths:
  /users:
    get:
      summary: Liste paginée des utilisateurs
      parameters:
        - $ref: '#/components/parameters/PageParam'
        - $ref: '#/components/parameters/SizeParam'
      responses:
        '200':
          description: Liste des utilisateurs retrouvés
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/User' }
        '400':
          description: Mauvais types de paramètres fournis
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
