openapi: 3.0.3
info:
  title: TD OAS - Exo 3 - Tasks
  version: 1.0.0
servers:
  - url: https://api.example.com
components:
  schemas:
    Task:
      type: object
      required: [id, title, completed]
      properties:
        id: { type: integer, example: 1 }
        title: { type: string, example: Faire les courses }
        completed: { type: boolean, example: false }
    TaskCreate:
      type: object
      required: [title, completed]
      properties:
        title: { type: string }
        completed: { type: boolean }
    IdList:
      type: array
      items: { type: integer }
paths:
  /tasks:
    get:
      summary: Lister les tâches
      responses:
        '200':
          description: Liste de tâches
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/Task' }
    post:
      summary: Créer une liste de nouvelles tâches
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items: { $ref: '#/components/schemas/TaskCreate' }
      responses:
        '201':
          description: Liste de tâches nouvellement créées
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/Task' }
    delete:
      summary: Supprimer une liste de tâches par identifiants
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/IdList' }
      responses:
        '200':
          description: Liste des tâches supprimées
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/Task' }
  /tasks/{id}:
    get:
      summary: Récupérer une tâche par ID
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: Tâche trouvée
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Task' }
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string, example: Task not found }
    delete:
      summary: Supprimer une tâche par ID
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: Tâche supprimée
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Task' }
